# Generated by Django 3.0.4 on 2020-05-06 03:25

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='init_balance_currency',
            new_name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='init_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='VND', max_digits=10, null=True, verbose_name='balance'),
        ),
    ]
