# Generated by Django 3.0.4 on 2020-05-06 03:50

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200506_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='VND', max_digits=15, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('Money', 'Tiền mặt'), ('Digital', 'Ví điện tử'), ('Card', 'Thẻ ngân hàng'), ('Credit', 'Thẻ ghi nợ')], default='Tiền mặt', max_length=255),
        ),
    ]
