# Generated by Django 3.0.4 on 2020-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, unique=True)),
                ('cat_types', models.CharField(choices=[('bill_utils', 'Bills & Utilities'), ('families', 'Families'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('health', 'Health')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('BASIC', 'Tiền mặt'), ('DIGITAL', 'Ví điện tử'), ('CARD', 'Thẻ ngân hàng'), ('CREDIT', 'Thẻ ghi nợ')], max_length=255),
        ),
    ]
