# Generated by Django 3.0.4 on 2020-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20200506_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
