# Generated by Django 3.0.4 on 2020-05-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_categories_cat_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Categories'),
        ),
    ]
