# Generated by Django 3.0.4 on 2020-05-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20200506_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='cat_types',
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wallet.Categories'),
        ),
    ]
