# Generated by Django 3.0.4 on 2020-05-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20200506_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='wallet.Categories'),
        ),
    ]
