version: '3.7'

services:
  web:
    build: ./backend/moneymon
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - ./backend/moneymon/.env.dev
    depends_on:
      - db
  ui:
    build: ./frontend
    ports:
        - 3001:80
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=moneymon_db

volumes:
  postgres_data: