//Auth
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
//Common
export const REQUEST_STARTED = "REQUEST_STARTED";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";

//Trasaction
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const TRASACTION_LIST = "TRASACTION_LIST";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";